// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arsijcpvyodrumqpvyfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyc2lqY3B2eW9kcnVtcXB2eWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTM4MzMsImV4cCI6MjA2OTE4OTgzM30.wueRLtvl5iGqwUEFgg2dG1sS6n96iyX1lBS-3GNzjmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});